version: '2'
services:
  web:
    image: alizapir/zipacote:v2
    shm_size: 128m
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "./:/zipacote"
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
